name: SGilfedder Portfolio
favicon: null
layout_spectrum: 0.39777723024599254
typography_spectrum: 0.4350098087452352
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.15306168608367443
  lightness: 0.6548286287579685
  saturation: 0.9895284662488848
  rhythmicContrast: 0.04416253138333559
purpose: []
