name: SGilfedder Portfolio
favicon: null
layout_spectrum: 1
typography_spectrum: 0.66532
title: Stuart Gilfedder Portfolio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffaa45'
    - '#c98a55'
    - '#1d1e23'
    - '#a3a2a8'
    - '#415577'
  brandStrength: 1
  lightness: 0.375
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
