typography_spectrum: 0.66532
color:
  brandColors:
    - '#ffaa45'
    - '#c98a55'
    - '#1d1e23'
    - '#a3a2a8'
    - '#415577'
  brandStrength: 1
  lightness: 0.375
  saturation: 0.375
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: SGilfedder Portfolio
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Corporate Events
    id: 6520d082-007f-46e6-8df0-5eb7069e8122
    type: content
favicon: null
title: Stuart Gilfedder Portfolio
purpose: []
